/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  newbieSidebar: [
    "getting-started/hello-world/index",
    "getting-started/icp-overview/index",
    "getting-started/dev-workflow/index",
    "getting-started/install-dfx/index",
    "getting-started/dev-account/index",
    "getting-started/get-cycles/index",
    "getting-started/ic-glossary/index",
    "getting-started/use-dfx/index",
  ],

  veteranSidebar: [
    {
      type: "category",
      label: "智能合约",
      items: [
        "dev-advanced/smart-contract/overview",
        "dev-advanced/smart-contract/write",
      ]
    },
  ],

  devSidebar: [
    {
      type: 'category',
      label: "Motoko 基础教程",
      items: [
        "dev-course/motoko/basic-0",
        "dev-course/motoko/basic-1",
        "dev-course/motoko/basic-2",
        "dev-course/motoko/basic-3",
        "dev-course/motoko/basic-4",
        "dev-course/motoko/basic-5",
      ]
    }
  ],

  sampleSidebar: [
    "code-examples/threshold-ecdsa/index",
    "code-examples/threshold-schnorr/index",
    "code-examples/btc-integration/index",
    "code-examples/ii-integration/index",
    "code-examples/https-outcalls/index",
    "code-examples/certified-variables/index",
    "code-examples/dfx-dependencies/index",
    "code-examples/canister-logs/index",
    "code-examples/canister-snapshot/index",
    "code-examples/wasm-simd/index",
  ],

  introSidebar: [{type: 'autogenerated', dirName: 'intro-ic'}],

  ecoSidebar: [
    "ecosystem-guide/dev-grants/index",
    "ecosystem-guide/node-provider-faq/index",
    "ecosystem-guide/media-assets/index",
    "ecosystem-guide/co-marketing/index",
    "ecosystem-guide/showcase/index",
  ],

  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}],
};

module.exports = sidebars;
